const playlist = [
  { title: "Constant Moderato", videoId: "SHkF48SgiSA" },
  { title: "Luminous Memory", videoId: "D3boxTP-ZG8" },
  { title: "Mischievous Step", videoId: "FHW2fNPaHU4" },
  { title: "Lovely Picnic", videoId: "dEfXiVI1Euo" },
  { title: "Colorful Mess", videoId: "OF9cu3cutj0" },
  { title: "Funky Road", videoId: "8h458BG1-Bo" },
  { title: "Unwelcome School", videoId: "pEg_d2f6myw" },
  { title: "Shady Girls", videoId: "v7s-gHSs-YM" },
  { title: "Midsummer Cat", videoId: "jokHmrFq56E" },
  { title: "Romantic Smile", videoId: "EBnOCXXg91o" },
  { title: "Connected Sky", videoId: "DzhcJxrS5Z8" },
  { title: "Shooting Stars", videoId: "yfsqGCO_ZfM" },
  { title: "Barrier", videoId: "phqb4ifkTrE" },
  { title: "Step by Step", videoId: "kuacQoR4U8I" },
  { title: "Honey Jam", videoId: "x-2yKahdTpg" },
  { title: "MX Adventure", videoId: "u6PbenoJSys" },
  { title: "Irasshaimase", videoId: "jHSozMn7GgA" },
  { title: "Mechanical JUNGLE", videoId: "JhWiVeXf2JM" },
  { title: "Virtual Storm", videoId: "vCvjZB8PqMQ" },
  { title: "Tech N Tech", videoId: "bg0GKgxO9lo" },
  { title: "Midnight Trip", videoId: "KopFUu0F4gk" },
  { title: "Daily Routine 24/7", videoId: "fTW7D5u0HfE" },
  { title: "Party Time", videoId: "XC0UwqE13U8" },
  { title: "Endless Carnival", videoId: "eOUzJN-W-rE" },
  { title: "Future Bossa", videoId: "kiwWb_1KFKs" },
  { title: "Lemonade Diary", videoId: "WECXxQnpBPE" },
  { title: "Fade Out", videoId: "v6Zw9m89CS8" },
  { title: "Plug and Play", videoId: "UqKlf3sOo3I" },
  { title: "Alert", videoId: "EDJttssxhuA" },
  { title: "Crossfire", videoId: "AqBVDJDB0ps" },
  { title: "Hello to Halo", videoId: "X64iuwOr3jg" },
  { title: "GGF", videoId: "skr-e1x4wy4" },
  { title: "Vivid Night", videoId: "1Z48Tb_eA6E" },
  { title: "Aoharu", videoId: "Oeedwk9oQLk" },
  { title: "Morose Dreamer", videoId: "Xyz-27ooAfU" },
  { title: "Koi is Love", videoId: "lzUS9plwjoQ" },
  { title: "Aira", videoId: "68DmAFofrlw" },
  { title: "Guruguru Usagi", videoId: "rpOxGU1CssA" },
  { title: "Water Drop", videoId: "0vpYgve07W8" },
  { title: "Neo City Dive", videoId: "VjdZmDzbZzk" },
  { title: "Interface", videoId: "kvWf9z02tIw" },
  { title: "Glitch Street", videoId: "XOY9xsXeYWk" },
  { title: "KIRISAME", videoId: "-xbqe_gYt1A" },
  { title: "Walkthrough", videoId: "m6qyju6JaR4" },
  { title: "Signal of Abydos", videoId: "TvTeVmFhpjw" },
  { title: "Sugar Story", videoId: "CuifrehnDBY" },
  { title: "Coffee Cats", videoId: "6iB1JvaE7_E" },
  { title: "Out of Control", videoId: "vLT2mPiun_A" },
  { title: "Mechanical JUNGLE (Hi-Tech Full On Mix)", videoId: "ojIwe8Ila3Y" },
  { title: "Hue", videoId: "boY1b3lD5oY" },
  { title: "ARES", videoId: "XObIfKNqKrE" },
  { title: "Vibes", videoId: "NGpguO2oO0A" },
  { title: "Future Lab", videoId: "h2o8ohARNZo" },
  { title: "After The Beep", videoId: "rbP2oyG2oPM" },
  { title: "Moment", videoId: "icycOtSlAmU" },
  { title: "Fearful Utopia", videoId: "hj2Xr1LRhlg" },
  { title: "Han-nari", videoId: "XDSJ9cnMezY" },
  { title: "SAKURA PUNCH", videoId: "lvHt8YXv_gc" },
  { title: "RE Aoharu", videoId: "lgq0OdRIEao" },
  { title: "SAKURA PUNCH (Hard Arrange)", videoId: "AHyfSGEuPEU" },
  { title: "Rolling Beat", videoId: "lKRgr_mO2jQ" },
  { title: "merry blue", videoId: "j80n-reoDrE" },
  { title: "Blooming Moon", videoId: "FQBN7y01YY0" },
  { title: "Pixel Time", videoId: "aL3MmoWOKMo" },
  { title: "Accelerator", videoId: "vNGl17i0zug" },
  { title: "Golden Shangri-la", videoId: "sx-nmPOmvO8" },
  { title: "someday, sometime", videoId: "F4V2pbyIEjs" },
  { title: "Virtual Storm (Hard Arrange)", videoId: "hidsgG934fg" },
  { title: "Snow Pantomime", videoId: "fyAOyaT5OxQ" },
  { title: "Black Suit", videoId: "glrUDKxsjwU" },
  { title: "Denshi Toujou!", videoId: "RM5h6JAtyTs" },
  { title: "Kaiten Screw!!!", videoId: "VBn8YhuMdm0" },
  { title: "Interface (Hard Arrange)", videoId: "kYAswwNTPD4" },
  { title: "Tech N Tech (Hard Arrange)", videoId: "Z_b24XEC8Q8" },
  { title: "Alert (Hard Arrange)", videoId: "d4XDBYg1Tzg" },
  { title: "Crossfire (Hard Arrange)", videoId: "RmvlrH2OjM8" },
  { title: "Burning Love", videoId: "AKkmWEr7jYY" },
  { title: "Fevertime", videoId: "JlfIWvaUNng" },
  { title: "Summer Bounce", videoId: "E-Q5CUybI4c" },
  { title: "Colorful Beach", videoId: "8omekhnCbl8" },
  { title: "Summer Bounce (Hard Arrange)", videoId: "9vyWEyuPggU" },
  { title: "Hifumi Daisuki", videoId: "ihqpgamoqbM" },
  { title: "PRST Academy", videoId: "YX8g_jg1XLs" },
  { title: "PRST Marching", videoId: "7K4v6eKqgQg" },
  { title: "Library of Omen", videoId: "rW4gMzdVO8s" },
  { title: "Summertime Archive", videoId: "yyhZgO9BBEw" },
  { title: "Constant Moderato Piano Arrange", videoId: "qz_G8rqofp0" },
  { title: "Oriental Drop", videoId: "AFlocwJFsWM" },
  { title: "The Dragon Express", videoId: "S5xzkx0Lshc" },
  { title: "FEEEEVER TIME", videoId: "oEfXyoHsPI4" },
  { title: "Crucial Issue", videoId: "uICPvVIcYlI" },
  { title: "Formless Dream", videoId: "QuhMoVQjI7U" },
  { title: "Bunny Bunny Carrot Carrot", videoId: "fLeFnN5tarI" },
  { title: "JACKPOT 777", videoId: "YOm5UvwBLgc" },
  { title: "OperationD", videoId: "RkUmdodpwvU" },
  { title: "Blue New Year", videoId: "-zBJ4RfT8ls" },
  { title: "Oxygen Destroyer", videoId: "CQGfCpfRArU" },
  { title: "Nesno wons", videoId: "Le0BSHu5-bQ" },
  { title: "Undefined Behavior", videoId: "_Df9xJBDPCY" },
  { title: "NRG FielD", videoId: "R5tigc-fGq4" },
  { title: "GIVE ME CHOCO♡", videoId: "w6SJPW6vW6s" },
  { title: "Poppin' Memories", videoId: "OrxJ0uKPBzU" },
  { title: "Cotton Candy Island", videoId: "eS4BAwDkraY" },
  { title: "Alkaline Tears", videoId: "Tntuxch3aUQ" },
  { title: "Blue New Battle", videoId: "_WJLkY7PcvU" },
  { title: "NERINERI CHALLENGE", videoId: "VjxfInALNFY" },
  { title: "Starting Pistol", videoId: "f9_dmfwIuKY" },
  { title: "Dolce Biblioteca", videoId: "h2VRu7Dk9D4" },
  { title: "Codex of Omen", videoId: "-CbkjQG7m38" },
  { title: "Usagi Flap", videoId: "toPWvdaC84w" },
  { title: "Unwelcome Guest", videoId: "rywA_nTYzIs" },
  { title: "Fall into the rabbit hole", videoId: "c-ALLjLqFmM" },
  { title: "IROHANI HOP", videoId: "GEHb2_aXoz8" },
  { title: "KARAKURhythm", videoId: "roGvSHsmpmU" },
  { title: "Agnus Dei", videoId: "ddQLkiEx8zk" },
  { title: "Blood Stained Faith", videoId: "epicS8VHog8" },
  { title: "Dive into Summer", videoId: "VhuZTu6j5LQ" },
  { title: "Na Na Natsu!", videoId: "sfGFtNrOvQc" },
  { title: "Underwater Jungle", videoId: "d8dIyfIGLQM" },
  { title: "Luxury Cool", videoId: "8_m5IPR0x8g" },
  { title: "TOMODACHI SUMMER", videoId: "jVWEqpo3uUk" },
  { title: "Kaphar", videoId: "Wr7sRXqBwR8" },
  { title: "Wave & Conquer", videoId: "IPDbzUwm7hY" },
  { title: "After School Dessert", videoId: "lz-jyS14WVI" },
  { title: "Let me think about it", videoId: "LC0KM4hb1wo" },
  { title: "Foolish Days", videoId: "cpqv73Xekr0" },
  { title: "Shooting Athletes", videoId: "n_TLq2H0OvI" },
  { title: "Raise the Huddle", videoId: "vHY0jdCrI8w" },
  { title: "Goal Wo Nerae!", videoId: "dOH0dXpDbaU" },
  { title: "Gestalt Angst", videoId: "91wNSrnRC9k" },
  { title: "Fruitful Blossom", videoId: "da22g5snShQ" },
  { title: "Kyrie Eleison", videoId: "90gEXwoPS9U" },
  { title: "Utaha No Uta", videoId: "iu_WbNBDnZg" },
  { title: "Cherry Merry Berry", videoId: "HwuRvtu6HlQ" },
  { title: "Defective Pixel", videoId: "j0lhxnFX7uo" },
  { title: "Tasty New Year", videoId: "mCTFH5Ih0Dk" },
  { title: "Encroached Sky", videoId: "eKHjTWzN4Y8" },
  { title: "!⸮ WAS IT A CAT I SAW ?!", videoId: "opJyEUVqmv8" },
  { title: "Hinagesi", videoId: "_ckBsAaAUoQ" },
  { title: "Polyphonic", videoId: "lSO2tjrABas" },
  { title: "Ark in the Blood Sky", videoId: "Q09ZkGJNDs4" },
  { title: "System All Green", videoId: "rxrquAmknuY" },
  { title: "Kaiten Hurricane!!!", videoId: "yvT7f6Zo4sA" },
  { title: "Aoharu Band Arrange", videoId: "n67Gh4OxpWA" },
  { title: "Responsibility", videoId: "RMoqYKDzUeM" },
  { title: "Final Destination of Ark", videoId: "Rm1GFl2xXEY" },
  { title: "Step of Terror", videoId: "RCQZ8DFKCcM" },
  { title: "Gregorius | Symphony", videoId: "LvSuEqpq_TM" },
  { title: "Operation☆DOTABATA", videoId: "OGTk9bExsII" },
  { title: "Noble Hallway", videoId: "BACrQlBAaDA" },
  { title: "Oriental Bounce", videoId: "nMFBbSPO5Hk" },
  { title: "Welcome School", videoId: "RmPUPU8Nwqw" },
  { title: "Trigger For Ambition", videoId: "0OPi2xx2KxA" },
  { title: "Kitsunebi", videoId: "goS8fzIV38A" },
  { title: "Up to 21°C", videoId: "JuQOQ4okSJE" },
  { title: "Hidden Treasure", videoId: "DNpVcwjD1S8" },
  { title: "Hunter Bible", videoId: "IgU9EhM4veM" },
  { title: "OTKPARA!", videoId: "joKV-NvDSpI" },
  { title: "Container Corner", videoId: "f53lYqM2UwU" },
  { title: "Rendezvous", videoId: "TyQfVl5ByA0" },
  { title: "Rendezvous (Recorder ver)", videoId: "RZrSYUOGUkM" },
  { title: "Takaramonogatari", videoId: "kKm2uutLzro" },
  { title: "Tok9 Train", videoId: "eWmQLvW9bjk" },
  { title: "HIGH-VELOCITY", videoId: "m9S5xxWQmhg" },
  { title: "Illuminated Night", videoId: "ZtjixQHFCzY" },
  { title: "Illuminated Night (Hard Arrange)", videoId: "2kr0xTvbJt0" },
  { title: "Tsukikage", videoId: "_KoieyIWooY" },
  { title: "Dark Shadows", videoId: "1cKu5mNkqw4" },
  { title: "PACHAD", videoId: "z5ulxk3JF7w" },
  { title: "Indoor Outdoor", videoId: "nuY9S6EeL_g" },
  { title: "Action 68", videoId: "g2uYkvC8VhA" },
  { title: "Dreaming Trip", videoId: "YsT_WI9op70" },
  { title: "Bluemark Canvas", videoId: "2mNAmP73qac" },
  { title: "Dancing Falsehood", videoId: "yEZlSGFouco" },
  { title: "F1ghtback", videoId: "aqD_lL7edNA" },
  { title: "Chilling Out", videoId: "2HRBQj3WF4U" },
  { title: "Starry Confession", videoId: "AUhKxTe6684" },
  { title: "Ridiculous", videoId: "q1Zx17Lef6s" },
  { title: "Nichirin", videoId: "RU3af2LshyE" },
  { title: "Getsurin", videoId: "_UltFdg4oS4" },
  { title: "SHANHAIJING Tragicomedy", videoId: "W4KPhd8Incc" },
  { title: "Yumeji Party", videoId: "KVCOcIbYtSs" },
  { title: "Serene Scenario", videoId: "xAf2WV8nVIg" },
  { title: "Realm Rumble", videoId: "iKfi8TvQThQ" },
  { title: "Ramune Lagoon", videoId: "rv1lxp_Xufs" },
  { title: "Summer Attack!", videoId: "yLBSYr5fVBw" },
  { title: "Let me go Seaside", videoId: "ISZ8lKOVapA" },
  { title: "HIGH5LANDER", videoId: "6ITgnMiM2DU" },
  { title: "Shoujo Delight", videoId: "NQPtBQhtTYQ" },
  { title: "Fury of Set", videoId: "GulGAXoLQ0o" },
  { title: "Miracle", videoId: "cP6Y-G9HHJg" },
  { title: "Shoujo Sorrow", videoId: "uuJfP7yVhGM" },
  { title: "Achromatic Prism", videoId: "Nw-FTURpHek" },
  { title: "Our Oath", videoId: "8LJC1Lpbnto" },
  { title: "Dazzle Everyday", videoId: "u7zJuM_ufso" },
  { title: "U mak3 m3 smil3", videoId: "-RuHM6cSrkw" },
  { title: "Candy Step", videoId: "hnZI7HV1J7A" },
  { title: "Scarlet Chrysanthemum", videoId: "9a_e1191O-o" },
  { title: "Flip Flap Festival!", videoId: "FXujDNyQ7gU" },
  { title: "Prophets", videoId: "efCyTDuEvP8" },
  { title: "Tremendous Celebration", videoId: "8leTKCXsa4Y" },
  { title: "0k@eri", videoId: "I7A-xuDS-rA" },
  { title: "Sudden Onset Disaster", videoId: "wTfRrbi72uw" },
  { title: "Oukaranman", videoId: "H4JnF1VtNlY" },
  { title: "U-n.I", videoId: "bGicz6yyFQc" },
  { title: "Sugary Holiday", videoId: "3P7zDw5UFNo" },
  { title: "P.A.J.A.M.A Sleep Over", videoId: "Wv9XsIYctjg" },
  { title: "DAN! DAN!! INVADER!!!", videoId: "ZG3Mc2gM5_g" },
  { title: "Expo Festa", videoId: "l4ZJmw8J918" },
  { title: "Mission Possible", videoId: "SPrBLc_KVd4" },
  { title: "WE'RE CCC", videoId: "8pi6ztlikIQ" },
  { title: "Sweet Allegro", videoId: "HTl_f6fQBjM" },
  { title: "Breaking Silence", videoId: "L7C-hty7ONg" },
  { title: "Love Story", videoId: "Q9zuTntcFFc" },
  { title: "Shining Seaside", videoId: "GHaS6h4UZaA" },
  { title: "You’re My Princess", videoId: "SFETQKiqPu4" },
];
